language: node_js
node_js:
  - "4.1.1"
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  
notifications:
  webhooks: 
    urls:
      - https://5laiixcwa1.execute-api.eu-west-1.amazonaws.com/1/webhooks/travis-ci
